sudo: false
os: linux
language: node_js
node_js:
  - "lts/*"
  - "11"
  - "12"
env:
  - TEST_SUITE=unit
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=standard
    - node_js: "lts/*"
      env: TEST_SUITE=coverage
script: npm run-script $TEST_SUITE
