sudo: false
os: linux
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "io.js"
  - "4"
  - "5"
  - "6"
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=unit
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint
script: npm run-script $TEST_SUITE
