sudo: false
os: linux
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
env:
  - TEST_SUITE=unit
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=coverage
    - node_js: "6"
      env: TEST_SUITE=lint
script: npm run-script $TEST_SUITE
